variable "environment" {}
variable "region" {}
variable "write_capacity" {}
variable "read_capacity" {}
variable "jwt_secret" {}
variable "admin_user_name" {}
variable "admin_user_email" {}
variable "admin_user_role" {}
variable "admin_user_id" {}
variable "admin_user_password" {}
